#include "oss_media_define.h"

char OSS_MEDIA_USER_AGENT[] = "oss_media";

int OSS_MEDIA_FILE_NOT_FOUND = 404;
char OSS_MEDIA_FILE_UNKNOWN_TYPE[] = "unknown";

int OSS_MEDIA_FILE_NUM_PER_LIST = 1000;
int OSS_MEDIA_INTERNAL_ERROR_CODE = 500;
int OSS_MEDIA_OK = 200;
int OSS_MEDIA_DEFAULT_WRITE_BUFFER = 256 * 1024; // 256K

int OSS_MEDIA_DEFAULT_VIDEO_PID = 256;
int OSS_MEDIA_DEFAULT_AUDIO_PID = 257;

int OSS_MEDIA_MP3_SAMPLE_RATE = 1158;
int OSS_MEDIA_AAC_SAMPLE_RATE = 1024;

int OSS_MEDIA_PAT_INTERVAL_FRAME_COUNT = 19;

char OSS_MEDIA_TS_FILE_SURFIX[] = ".ts";
char OSS_MEDIA_M3U8_FILE_SURFIX[] = ".m3u8";
